name: Learn and Test

on:
  push:

jobs:
  print-info:
    runs-on: windows-latest
    steps:
      - name: Get System info
        run: systeminfo
      # - name: Install fastfetch
      #   run: winget search fastfetch
      - name: Setup Rust with MSVC toolchain
        run: |
          # 安装 Rust toolchain，并指定 MSVC 目标
          rustup toolchain install stable-x86_64-pc-windows-msvc
          rustup default stable-x86_64-pc-windows-msvc
          
          # 可选：验证安装
          rustc --version
          cargo --version