name: Test all languages on Windows

on:
  push:
    branches:
      - main

jobs:
  verify-environments:
    runs-on: windows-latest

    steps:
      - name: Check all pre-installed language environments
        run: |
          echo "--- Verifying Rust ---"
          rustc --version
          cargo --version
          
          echo "--- Verifying Python ---"
          python --version
          pip --version
          
          echo "--- Verifying Node.js ---"
          node --version
          npm --version
          
          echo "--- Verifying Go ---"
          go version
          
          echo "--- Verifying Ruby ---"
          ruby --version
          
          echo "--- Verifying Java ---"
          java -version
          
          echo "--- Verifying C++ (MSVC) ---"
          cl